name: Docker Image CI

on:
  push:

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: "recursive"

    - name: Build the Docker image
      run: docker build . --label "org.opencontainers.image.source=https://github.com/DelusionalLogic/dht" --file Dockerfile --tag app

    - name: Push the image
      run: |
        docker push app ghcr.io/delusionallogic/dht:1.${{ github.run_number }}
        docker push app ghcr.io/delusionallogic/dht:latest
